### ISSUE TITLE
Arduino Due

### ISSUE THREAD

**Issue by Dabren** [StroudCenter/Arduino-SDI-12#9]
Hi,

If I want to use an Arduino Due to communicate with a sensor that uses the SDI12 protocol, how should I connect them instead? 

Thanks.

**Comment by matiasAS** [comment]
Hola @s-hicks2, con que arduino dices que te funciona sdi-12, con arduino ¿Due especificamente?

**Comment by SRGDamia1** [comment]
I'd assume the CS655 should work with the library.  I don't have one and don't know anything about it.

The Arduino Due, however, is not supported.  From what I've read the Due is not designed to be a low-power board and thus is not a good choice for long-term in-situ monitoring with environmental sensors.  It also doesn't seem to be a very popular board.  And I don't have one.  Those things, combined with the fact that the Due uses a different interrupt system than any of the boards that are supported, mean that Due is unlikely to ever be supported.

**Comment by matiasAS** [comment]
Hola Sara,
Gracias por responder
Matías
